#!/usr/bin/env python3
"""Strip laboratory metadata from a blog draft for Substack paste/upload."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

DROP_SECTIONS = (
    "## Publication checklist",
)
DROP_LINES_PREFIX = (
    "**Status:**",
    "**Case:**",
    "**Identifiers:**",
    "*Draft generated by",
)


def export_for_substack(source: Path, dest: Path) -> None:
    text = source.read_text(encoding="utf-8")
    lines = text.splitlines()
    out: list[str] = []
    skip_section = False

    for line in lines:
        if any(line.startswith(prefix) for prefix in DROP_LINES_PREFIX):
            continue
        if line.startswith("## ") and any(line.startswith(s) for s in DROP_SECTIONS):
            skip_section = True
            continue
        if skip_section:
            if line.startswith("## ") and not any(line.startswith(s) for s in DROP_SECTIONS):
                skip_section = False
            else:
                continue
        if line.strip() == "---" and not out:
            continue
        out.append(line)

    body = "\n".join(out).strip() + "\n"
    # Substack: relative figure paths → operator upload reminder
    body = re.sub(
        r"!\[([^\]]*)\]\(\.\./06_Visualizations/([^)]+)\)",
        r"![\1](<!-- UPLOAD: 06_Visualizations/\2 -->)",
        body,
    )
    meta = (
        "<!-- SUBSTACK METADATA (operator — remove before publish or paste into Substack fields)\n"
        "Title: Same Metres, Different Tax: Paired Residual Analysis on Sandnes Ultra Trail\n"
        "Subtitle: Phase B TRF on SUT_43 — full-lap dilution vs corridor slice friction\n"
        "Byline: Dr. Anatomy Pace\n"
        "Tags: terrain index, ultra running, Rogaland, biomechanics, data science\n"
        "Figures (upload in order): sut43_gramstad_friction_strip_blog.png, "
        "sut43_trf_dilution_blog.png, sut43_gramstad_paired_trf_blog.png\n"
        "-->\n\n"
    )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(meta + body, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--dest", type=Path, required=True)
    args = parser.parse_args()
    export_for_substack(args.source, args.dest)
    print(f"OK Substack export → {args.dest}")


if __name__ == "__main__":
    main()
